const AI_ICON_BASE = {
    "24-hours": "24-hours",
    "4k": "4k",
    //accessibility: "accessibility", Não funciona
    "account-circle": "account-circle",
    "account-pin-circle": "account-pin",
    add: "add",
    "add-circle": "add-circle",
    admin: "admin",
    advertisement: "advertisement",
    aed: "aed",
    "aed-electrodes": "aed-electrodes",
    airplay: "airplay",
    alarm: "alarm",
    "alarm-snooze": "alarm-snooze",
    "alarm-warning": "alarm-warning",
    album: "album",
    alert: "alert",
    "alibaba-cloud": "alibaba-cloud",
    aliens: "aliens",
    "align-item-bottom": "align-item-bottom",
    "align-item-horizontal-center": "align-item-horizontal-center",
    "align-item-left": "align-item-left",
    "align-item-right": "align-item-right",
    "align-item-top": "align-item-top",
    "align-item-vertical-center": "align-item-vertical-center",
    alipay: "alipay",
    amazon: "amazon",
    anchor: "anchor",
    "ancient-gate": "ancient-gate",
    "ancient-pavilion": "ancient-pavilion",
    android: "android",
    angularjs: "angularjs",
    anthropic: "anthropic",
    anticlockwise: "anticlockwise",
    "app-store": "app-store",
    apple: "apple",
    apps: "apps",
    "apps-2-ai": "apps-ai",
    archive: "archive",
    //"area-chart": "area-chart",
    armchair: "armchair",
    "arrow-down": "arrow-down",
    "arrow-right": "arrow-right",
    "arrow-left": "arrow-left",
    "arrow-up": "arrow-up",
    "arrow-left-up": "arrow-left-up",
    "arrow-left-down": "arrow-left-down",
    "arrow-right-up": "arrow-right-up",
    "arrow-right-down": "arrow-right-down",
    "arrow-left-right": "arrow-left-right",
    "arrow-up-down": "arrow-up-down",
    "arrow-down-circle": "arrow-down-circle",
    "arrow-left-circle": "arrow-left-circle",
    "arrow-up-circle": "arrow-up-circle",
    "arrow-right-circle": "arrow-right-circle",
    "arrow-down-double": "arrow-down-double",
    "arrow-left-double": "arrow-left-double",
    "arrow-right-double": "arrow-right-double",
    "arrow-up-double": "arrow-up-double",
    "arrow-left-s": "arrow-left-s",
    "arrow-down-s": "arrow-down-s",
    "arrow-right-s": "arrow-right-s",
    "arrow-up-s": "arrow-up-s",
    "arrow-down-long": "arrow-down-long",
    "arrow-left-down-long": "arrow-left-down-long",
    "arrow-left-long": "arrow-left-long",
    "arrow-left-up-long": "arrow-left-up-long",
    "arrow-right-down-long": "arrow-right-down-long",
    "arrow-right-long": "arrow-right-long",
    "arrow-right-up-long": "arrow-right-up-long",
    "arrow-up-long": "arrow-up-long",
    "arrow-go-back": "arrow-go-back",
    "arrow-turn-back": "arrow-turn-back",
    "arrow-go-forward": "arrow-go-forward",
    "arrow-turn-forward": "arrow-turn-forward",
    artboard: "artboard",
    article: "article",
    "aspect-ratio": "aspect-ratio",
    at: "at",
    //atom: "atom",
    "attachment-2": "attachment",
    auction: "auction",
    award: "award",
    baidu: "baidu",
    "ball-pen": "ball-pen",
    bank: "bank",
    "bank-card": "bank-card",
    "bar-chart-2": "bar-chart",
    "bar-chart-grouped": "bar-chart-grouped",
    "bar-chart-horizontal": "bar-chart-horizontal",
    barcode: "barcode",
    bard: "bard",
    barricade: "barricade",
    "base-station": "base-station",
    //baseball: "baseball",
    basketball: "basketball",
    battery: "battery",
    "battery-charge": "battery-charge",
    "battery-low": "battery-low",
    "battery-saver": "battery-saver",
    "bear-smile": "bear-smile",
    beer: "beer",
    behance: "behance",
    bell: "bell",
    bike: "bike",
    bilibili: "bilibili",
    bill: "bill",
    billiards: "billiards",
    //binoculars: "binoculars",
    "bit-coin": "bit-coin",
    blaze: "blaze",
    blender: "blender",
    blogger: "blogger",
    bluesky: "bluesky",
    bluetooth: "bluetooth",
    "blur-off": "blur-off",
    bnb: "bnb",
    "body-scan": "body-scan",
    "book-2": "book",
    "book-marked": "book-marked",
    "book-open": "book-open",
    booklet: "booklet",
    bootstrap: "bootstrap",
    bowl: "bowl",
    "box-3": "box",
    boxing: "boxing",
    braces: "braces",
    brackets: "brackets",
    brain: "brain",
    bread: "bread",
    briefcase: "briefcase",
    broadcast: "broadcast",
    brush: "brush",
    "brush-3": "brush-3",
    btc: "btc",
    "bubble-chart": "bubble-chart",
    bug: "bug",
    building: "building",
    "building-4": "building-4",
    bus: "bus",
    "bus-2": "bus-2",
    "bus-wifi": "bus-wifi",
    cactus: "cactus",
    cake: "cake",
    "cake-2": "cake-2",
    "cake-3": "cake-3",
    calculator: "calculator",
    calendar: "calendar",
    "calendar-check": "calendar-check",
    "calendar-close": "calendar-close",
    "calendar-event": "calendar-event",
    "calendar-schedule": "calendar-schedule",
    "calendar-todo": "calendar-todo",
    camera: "camera",
    "camera-lens": "camera-lens",
    "camera-off": "camera-off",
    "camera-switch": "camera-switch",
    candle: "candle",
    capsule: "capsule",
    car: "car",
    "car-washing": "car-washing",
    caravan: "caravan",
    cash: "cash",
    cast: "cast",
    cellphone: "cellphone",
    celsius: "celsius",
    centos: "centos",
    //certificate: "certificate",
    "character-recognition": "character-recognition",
    "charging-pile": "charging-pile",
    "charging-pile-2": "charging-pile-2",
    "chat-1": "chat-1",
    "chat-check": "chat-check",
    "chat-delete": "chat-delete",
    "chat-download": "chat-download",
    "chat-follow-up": "chat-follow-up",
    "chat-forward": "chat-forward",
    "chat-heart": "chat-heart",
    "chat-history": "chat-history",
    "chat-new": "chat-new",
    "chat-off": "chat-off",
    "chat-poll": "chat-poll",
    "chat-private": "chat-private",
    "chat-quote": "chat-quote",
    "chat-search": "chat-search",
    "chat-settings": "chat-settings",
    "chat-thread": "chat-thread",
    "chat-unread": "chat-unread",
    "chat-upload": "chat-upload",
    "chat-voice": "chat-voice",
    "chat-voice-ai": "chat-voice-ai",
    check: "check",
    "check-double": "check-double",
    checkbox: "checkbox",
    "checkbox-blank": "checkbox-blank",
    "checkbox-blank-circle": "checkbox-blank-circle",
    "checkbox-circle": "checkbox-circle",
    "checkbox-indeterminate": "checkbox-indeterminate",
    "checkbox-multiple": "checkbox-multiple",
    "checkbox-multiple-blank": "checkbox-multiple-blank",
    //chess: "chess",
    "china-railway": "china-railway",
    chrome: "chrome",
    circle: "circle",
    clapperboard: "clapperboard",
    claude: "claude",
    clipboard: "clipboard",
    clockwise: "clockwise",
    close: "close",
    "close-circle": "close-circle",
    "closed-captioning": "closed-captioning",
    cloud: "cloud",
    "cloud-off": "cloud-off",
    "cloud-windy": "cloud-windy",
    cloudy: "cloudy",
    code: "code",
    "code-block": "code-block",
    "code-s-slash": "code-s-slash",
    codepen: "codepen",
    coin: "coin",
    coins: "coins",
    collage: "collage",
    "collapse-diagonal": "collapse-diagonal",
    "collapse-horizontal": "collapse-horizontal",
    "collapse-vertical": "collapse-vertical",
    "color-filter": "color-filter",
    command: "command",
    community: "community",
    "compass-3": "compass",
    "compass-discover": "compass-discover",
    compasses: "compasses",
    computer: "computer",
    //connector: "connector",
    contacts: "contacts",
    "contacts-book": "contacts-book",
    "contacts-book-upload": "contacts-book-upload",
    contract: "contract",
    "contract-left": "contract-left",
    "contract-left-right": "contract-left-right",
    "contract-right": "contract-right",
    "contract-up-down": "contract-up-down",
    contrast: "contrast",
    "contrast-drop": "contrast-drop",
    "contrast-drop-2": "contrast-drop-2",
    //cookie: "cookie",
    copilot: "copilot",
    "copper-coin": "copper-coin",
    "copper-diamond": "copper-diamond",
    copyleft: "copyleft",
    copyright: "copyright",
    coreos: "coreos",
    "corner-down-left": "corner-down-left",
    "corner-down-right": "corner-down-right",
    "corner-left-down": "corner-left-down",
    "corner-left-up": "corner-left-up",
    "corner-right-down": "corner-right-down",
    "corner-right-up": "corner-right-up",
    "corner-up-left": "corner-up-left",
    "corner-up-left-double": "corner-up-left-double",
    "corner-up-right": "corner-up-right",
    "corner-up-right-double": "corner-up-right-double",
    coupon: "coupon",
    cpu: "cpu",
    "creative-commons": "creative-commons",
    "creative-commons-by": "creative-commons-by",
    "creative-commons-nc": "creative-commons-nc",
    "creative-commons-nd": "creative-commons-nd",
    "creative-commons-sa": "creative-commons-sa",
    "creative-commons-zero": "creative-commons-zero",
    criminal: "criminal",
    crop: "crop",
    "crop-2": "crop-2",
    cross: "cross",
    crosshair: "crosshair",
    css3: "css3",
    cup: "cup",
    currency: "currency",
    cursor: "cursor",
    "customer-service-2": "customer-service",
    dashboard: "dashboard",
    "dashboard-2": "dashboard-2",
    "database-2": "database",
    //deepseek: "deepseek",
    "delete-back": "delete-back",
    "delete-back-2": "delete-back-2",
    "delete-bin": "delete-bin",
    "delete-bin-2": "delete-bin-2",
    device: "device",
    "device-recover": "device-recover",
    //diamond: "diamond",
    //"diamond-ring": "diamond-ring",
    dice: "dice",
    dingding: "dingding",
    direction: "direction",
    disc: "disc",
    discord: "discord",
    "discount-percent": "discount-percent",
    discuss: "discuss",
    dislike: "dislike",
    disqus: "disqus",
    divide: "divide",
    dna: "dna",
    "donut-chart": "donut-chart",
    "door-closed": "door-closed",
    "door-lock": "door-lock",
    "door-open": "door-open",
    dossier: "dossier",
    douban: "douban",
    download: "download",
    "download-cloud-2": "download-cloud",
    draft: "draft",
    "drag-drop": "drag-drop",
    "drag-move-2": "drag-move",
    //draw: "draw",
    dribbble: "dribbble",
    drinks: "drinks",
    drive: "drive",
    drizzle: "drizzle",
    drop: "drop",
    dropbox: "dropbox",
    dropper: "dropper",
    "dual-sim-1": "dual-sim-1",
    "dual-sim-2": "dual-sim-2",
    dv: "dv",
    dvd: "dvd",
    "e-bike-2": "e-bike",
    earth: "earth",
    earthquake: "earthquake",
    edge: "edge",
    "edge-new": "edge-new",
    edit: "edit",
    eject: "eject",
    "emoji-sticker": "emoji-sticker",
    emotion: "emotion",
    "emotion-2": "emotion-2",
    //"emotion-add": "emotion-add",
    "emotion-happy": "emotion-happy",
    "emotion-laugh": "emotion-laugh",
    "emotion-normal": "emotion-normal",
    "emotion-sad": "emotion-sad",
    "emotion-unhappy": "emotion-unhappy",
    empathize: "empathize",
    //"english-input": "english-input",
    equal: "equal",
    equalizer: "equalizer",
    eraser: "eraser",
    "error-warning": "error-warning",
    eth: "eth",
    evernote: "evernote",
    exchange: "exchange",
    "exchange-cny": "exchange-cny",
    "exchange-dollar": "exchange-dollar",
    "exchange-funds": "exchange-funds",
    "expand-diagonal": "expand-diagonal",
    "expand-diagonal-s": "expand-diagonal-s",
    "expand-height": "expand-height",
    "expand-horizontal": "expand-horizontal",
    "expand-horizontal-s": "expand-horizontal-s",
    "expand-left": "expand-left",
    "expand-left-right": "expand-left-right",
    "expand-right": "expand-right",
    "expand-up-down": "expand-up-down",
    "expand-vertical": "expand-vertical",
    "expand-vertical-s": "expand-vertical-s",
    "expand-width": "expand-width",
    export: "export",
    "external-link": "external-link",
    eye: "eye",
    "eye-close": "eye-close",
    "eye-off": "eye-off",
    facebook: "facebook",
    "facebook-circle": "facebook-circle",
    fahrenheit: "fahrenheit",
    fediverse: "fediverse",
    feedback: "feedback",
    //figma: "figma",
    file: "file",
    "file-add": "file-add",
    "file-chart": "file-chart",
    "file-check": "file-check",
    "file-close": "file-close",
    "file-cloud": "file-cloud",
    "file-code": "file-code",
    "file-copy": "file-copy",
    "file-damage": "file-damage",
    "file-download": "file-download",
    "file-edit": "file-edit",
    "file-excel": "file-excel",
    "file-forbid": "file-forbid",
    "file-gif": "file-gif",
    "file-history": "file-history",
    "file-hwp": "file-hwp",
    "file-image": "file-image",
    "file-info": "file-info",
    "file-list": "file-list",
    "file-lock": "file-lock",
    "file-marked": "file-marked",
    "file-music": "file-music",
    "file-paper": "file-paper",
    "file-pdf-2": "file-pdf",
    "file-ppt": "file-ppt",
    "file-reduce": "file-reduce",
    //"file-scan": "file-scan",
    "file-search": "file-search",
    "file-settings": "file-settings",
    "file-shield": "file-shield",
    "file-shred": "file-shred",
    "file-text": "file-text",
    "file-transfer": "file-transfer",
    "file-unknow": "file-unknow",
    "file-upload": "file-upload",
    "file-user": "file-user",
    "file-video": "file-video",
    "file-warning": "file-warning",
    "file-word": "file-word",
    "file-zip": "file-zip",
    film: "film",
    filter: "filter",
    "filter-off": "filter-off",
    "find-replace": "find-replace",
    finder: "finder",
    fingerprint: "fingerprint",
    fire: "fire",
    firebase: "firebase",
    firefox: "firefox",
    //"firefox-browser": "firefox-browser",
    //fiverr: "fiverr",
    flag: "flag",
    "flag-off": "flag-off",
    flashlight: "flashlight",
    flask: "flask",
    flickr: "flickr",
    "flight-land": "flight-land",
    "flight-takeoff": "flight-takeoff",
    "flip-horizontal": "flip-horizontal",
    "flip-vertical": "flip-vertical",
    flood: "flood",
    "flow-chart": "flow-chart",
    flower: "flower",
    flutter: "flutter",
    "focus-2": "focus",
    foggy: "foggy",
    folder: "folder",
    "folder-add": "folder-add",
    "folder-chart": "folder-chart",
    "folder-check": "folder-check",
    "folder-close": "folder-close",
    "folder-cloud": "folder-cloud",
    "folder-download": "folder-download",
    "folder-forbid": "folder-forbid",
    "folder-history": "folder-history",
    "folder-image": "folder-image",
    "folder-info": "folder-info",
    "folder-keyhole": "folder-keyhole",
    "folder-lock": "folder-lock",
    "folder-music": "folder-music",
    "folder-open": "folder-open",
    "folder-received": "folder-received",
    "folder-reduce": "folder-reduce",
    "folder-settings": "folder-settings",
    "folder-shared": "folder-shared",
    "folder-shield": "folder-shield",
    "folder-transfer": "folder-transfer",
    "folder-unknow": "folder-unknow",
    "folder-upload": "folder-upload",
    "folder-user": "folder-user",
    "folder-video": "folder-video",
    "folder-warning": "folder-warning",
    "folder-zip": "folder-zip",
    folders: "folders",
    football: "football",
    footprint: "footprint",
    forbid: "forbid",
    "forward-10": "forward-10",
    "forward-15": "forward-15",
    "forward-30": "forward-30",
    "forward-5": "forward-5",
    "forward-end": "forward-end",
    "forward-end-mini": "forward-end-mini",
    fridge: "fridge",
    friendica: "friendica",
    fullscreen: "fullscreen",
    "fullscreen-exit": "fullscreen-exit",
    function: "function",
    "function-add": "function-add",
    functions: "functions",
    funds: "funds",
    gallery: "gallery",
    "gallery-upload": "gallery-upload",
    game: "game",
    gamepad: "gamepad",
    "gas-station": "gas-station",
    gatsby: "gatsby",
    gemini: "gemini",
    genderless: "genderless",
    ghost: "ghost",
    gift: "gift",
    "git-branch": "git-branch",
    "git-close-pull-request": "git-close-pull-request",
    "git-commit": "git-commit",
    "git-fork": "git-fork",
    "git-merge": "git-merge",
    "git-pr-draft": "git-pr-draft",
    "git-pull-request": "git-pull-request",
    "git-repository": "git-repository",
    "git-repository-commits": "git-repository-commits",
    "git-repository-private": "git-repository-private",
    //gitbook: "gitbook",
    //gitee: "gitee",
    github: "github",
    gitlab: "gitlab",
    glasses: "glasses",
    global: "global",
    //"global-off": "global-off",
    globe: "globe",
    goblet: "goblet",
    //"goblet-broken": "goblet-broken",
    goggles: "goggles",
    "golf-ball": "golf-ball",
    google: "google",
    "google-play": "google-play",
    government: "government",
    gps: "gps",
    gradienter: "gradienter",
    "graduation-cap": "graduation-cap",
    grid: "grid",
    "group-2": "group",
    guide: "guide",
    hail: "hail",
    hammer: "hammer",
    "hand-coin": "hand-coin",
    "hand-heart": "hand-heart",
    "hand-sanitizer": "hand-sanitizer",
    handbag: "handbag",
    "hard-drive": "hard-drive",
    haze: "haze",
    hd: "hd",
    heading: "heading",
    headphone: "headphone",
    "health-book": "health-book",
    heart: "heart",
    "heart-add": "heart-add",
    "heart-pulse": "heart-pulse",
    hearts: "hearts",
    "heavy-showers": "heavy-showers",
    hexagon: "hexagon",
    history: "history",
    home: "home",
    "home-gear": "home-gear",
    "home-heart": "home-heart",
    "home-office": "home-office",
    "home-smile-2": "home-smile",
    "home-wifi": "home-wifi",
    "honor-of-kings": "honor-of-kings",
    honour: "honour",
    hospital: "hospital",
    hotel: "hotel",
    "hotel-bed": "hotel-bed",
    hotspot: "hotspot",
    hourglass: "hourglass",
    hq: "hq",
    html5: "html5",
    "id-card": "id-card",
    ie: "ie",
    image: "image",
    "image-add": "image-add",
    "image-circle": "image-circle",
    //"image-download": "image-download",
    "image-edit": "image-edit",
    "image-upload": "image-upload",
    import: "import",
    inbox: "inbox",
    "inbox-archive": "inbox-archive",
    "inbox-unarchive": "inbox-unarchive",
    //"increase-decrease": "increase-decrease",
    "indeterminate-circle": "indeterminate-circle",
    infinity: "infinity",
    "info-card": "info-card",
    "info-i": "info-i",
    "information-2": "information",
    "information-off": "information-off",
    "infrared-thermometer": "infrared-thermometer",
    "ink-bottle": "ink-bottle",
    // "input-method": "input-method",
    instagram: "instagram",
    install: "install",
    instance: "instance",
    invision: "invision",
    //issues: "issues",
    //"issues-reopen": "issues-reopen",
    java: "java",
    javascript: "javascript",
    jewelry: "jewelry",
    "kakao-talk": "kakao-talk",
    key: "key",
    keyboard: "keyboard",
    keynote: "keynote",
    kick: "kick",
    knife: "knife",
    "knife-blood": "knife-blood",
    landscape: "landscape",
    layout: "layout",
    "layout-bottom": "layout-bottom",
    "layout-column": "layout-column",
    "layout-grid": "layout-grid",
    "layout-horizontal": "layout-horizontal",
    "layout-left": "layout-left",
    "layout-masonry": "layout-masonry",
    "layout-right": "layout-right",
    "layout-row": "layout-row",
    "layout-top": "layout-top",
    "layout-vertical": "layout-vertical",
    leaf: "leaf",
    "letter-spacing-2": "letter-spacing-2",
    lifebuoy: "lifebuoy",
    lightbulb: "lightbulb",
    "lightbulb-flash": "lightbulb-flash",
    line: "line",
    "line-chart": "line-chart",
    "line-height": "line-height",
    link: "link",
    linkedin: "linkedin",
    links: "links",
    "list-settings": "list-settings",
    live: "live",
    loader: "loader",
    "loader-2": "loader-2",
    "loader-3": "loader-3",
    "loader-4": "loader-4",
    "loader-5": "loader-5",
    lock: "lock",
    "lock-password": "lock-password",
    "lock-star": "lock-star",
    "lock-unlock": "lock-unlock",
    "login-circle": "login-circle",
    "logout-circle": "logout-circle",
    "logout-circle-r": "logout-circle-r",
    "loop-left": "loop-left",
    "loop-right": "loop-right",
    "luggage-cart": "luggage-cart",
    "luggage-deposit": "luggage-deposit",
    lungs: "lungs",
    mac: "mac",
    macbook: "macbook",
    magic: "magic",
    mail: "mail",
    "mail-add": "mail-add",
    "mail-check": "mail-check",
    "mail-close": "mail-close",
    "mail-download": "mail-download",
    "mail-forbid": "mail-forbid",
    "mail-lock": "mail-lock",
    "mail-open": "mail-open",
    "mail-send": "mail-send",
    "mail-settings": "mail-settings",
    "mail-star": "mail-star",
    "mail-unread": "mail-unread",
    "mail-volume": "mail-volume",
    "map-2": "map",
    "map-pin": "map-pin",
    "map-pin-add": "map-pin-add",
    "map-pin-range": "map-pin-range",
    "map-pin-time": "map-pin-time",
    "map-pin-user": "map-pin-user",
    "mark-pen": "mark-pen",
    markdown: "markdown",
    markup: "markup",
    mastercard: "mastercard",
    mastodon: "mastodon",
    medal: "medal",
    "medicine-bottle": "medicine-bottle",
    medium: "medium",
    megaphone: "megaphone",
    memories: "memories",
    men: "men",
    "mental-health": "mental-health",
    menu: "menu",
    "menu-add": "menu-add",
    "menu-fold": "menu-fold",
    "menu-search": "menu-search",
    "menu-unfold": "menu-unfold",
    message: "message",
    messenger: "messenger",
    meta: "meta",
    meteor: "meteor",
    mic: "mic",
    "mic-off": "mic-off",
    mickey: "mickey",
    microscope: "microscope",
    microsoft: "microsoft",
    //"microsoft-copilot": "microsoft-copilot",
    "microsoft-loop": "microsoft-loop",
    "mind-map": "mind-map",
    "mini-program": "mini-program",
    mist: "mist",
    mixtral: "mixtral",
    "mobile-download": "mobile-download",
    "money-cny-box": "money-cny-box",
    "money-cny-circle": "money-cny-circle",
    "money-dollar-circle": "money-dollar-circle",
    "money-euro-box": "money-euro-box",
    "money-euro-circle": "money-euro-circle",
    "money-pound-circle": "money-pound-circle",
    "money-rupee-circle": "money-rupee-circle",
    moon: "moon",
    "moon-clear": "moon-clear",
    "moon-cloudy": "moon-cloudy",
    "moon-foggy": "moon-foggy",
    more: "more",
    "more-2": "more-2",
    //mosaic: "mosaic",
    motorbike: "motorbike",
    mouse: "mouse",
    "movie-2": "movie",
    "multi-image": "multi-image",
    music: "music",
    mv: "mv",
    navigation: "navigation",
    "netease-cloud-music": "netease-cloud-music",
    netflix: "netflix",
    network: "network",
    "network-error": "network-error",
    "network-off": "network-off",
    news: "news",
    newspaper: "newspaper",
    nextjs: "nextjs",
    nft: "nft",
    "no-credit-card": "no-credit-card",
    nodejs: "nodejs",
    notification: "notification",
    "notification-off": "notification-off",
    "notification-snooze": "notification-snooze",
    notion: "notion",
    npmjs: "npmjs",
    numbers: "numbers",
    nurse: "nurse",
    octagon: "octagon",
    oil: "oil",
    "open-arm": "open-arm",
    "open-source": "open-source",
    openai: "openai",
    openbase: "openbase",
    opera: "opera",
    "order-play": "order-play",
    outlet: "outlet",
    p2p: "p2p",
    pages: "pages",
    paint: "paint",
    "paint-brush": "paint-brush",
    painting: "painting",
    palette: "palette",
    pantone: "pantone",
    parent: "parent",
    parentheses: "parentheses",
    parking: "parking",
    "pass-expired": "pass-expired",
    "pass-pending": "pass-pending",
    "pass-valid": "pass-valid",
    passport: "passport",
    patreon: "patreon",
    pause: "pause",
    "pause-circle": "pause-circle",
    paypal: "paypal",
    "pen-nib": "pen-nib",
    pencil: "pencil",
    "pencil-ruler-2": "pencil-ruler",
    pentagon: "pentagon",
    percent: "percent",
    perplexity: "perplexity",
    phone: "phone",
    "phone-camera": "phone-camera",
    "phone-find": "phone-find",
    "phone-lock": "phone-lock",
    php: "php",
    piano: "piano",
    "piano-grand": "piano-grand",
    "picture-in-picture": "picture-in-picture",
    "picture-in-picture-exit": "picture-in-picture-exit",
    "pie-chart": "pie-chart",
    "pin-distance": "pin-distance",
    "ping-pong": "ping-pong",
    pinterest: "pinterest",
    pix: "pix",
    pixelfed: "pixelfed",
    plane: "plane",
    planet: "planet",
    plant: "plant",
    play: "play",
    "play-circle": "play-circle",
    "play-list": "play-list",
    "play-list-add": "play-list-add",
    "play-reverse": "play-reverse",
    playstation: "playstation",
    plug: "plug",
    "poker-clubs": "poker-clubs",
    "poker-diamonds": "poker-diamonds",
    "poker-hearts": "poker-hearts",
    "poker-spades": "poker-spades",
    polaroid: "polaroid",
    "police-badge": "police-badge",
    "police-car": "police-car",
    presentation: "presentation",
    "price-tag-3": "price-tag",
    printer: "printer",
    "printer-cloud": "printer-cloud",
    "product-hunt": "product-hunt",
    profile: "profile",
    "progress-1": "progress-1",
    "progress-2": "progress-2",
    "progress-3": "progress-3",
    "progress-4": "progress-4",
    "progress-5": "progress-5",
    "progress-6": "progress-6",
    "progress-7": "progress-7",
    "progress-8": "progress-8",
    prohibited: "prohibited",
    projector: "projector",
    psychotherapy: "psychotherapy",
    pulse: "pulse",
    pushpin: "pushpin",
    "pushpin-2": "pushpin-2",
    puzzle: "puzzle",
    qq: "qq",
    "qr-code": "qr-code",
    "qr-scan": "qr-scan",
    question: "question",
    "question-answer": "question-answer",
    questionnaire: "questionnaire",
    "quill-pen": "quill-pen",
    radar: "radar",
    radio: "radio",
    "radio-button": "radio-button",
    rainbow: "rainbow",
    rainy: "rainy",
    ram: "ram",
    reactjs: "reactjs",
    receipt: "receipt",
    "record-circle": "record-circle",
    "record-mail": "record-mail",
    rectangle: "rectangle",
    recycle: "recycle",
    "red-packet": "red-packet",
    reddit: "reddit",
    refresh: "refresh",
    refund: "refund",
    registered: "registered",
    remix: "remix",
    "remix-run": "remix-run",
    remixicon: "remixicon",
    "remote-control": "remote-control",
    repeat: "repeat",
    "repeat-one": "repeat-one",
    "replay-10": "replay-10",
    "replay-15": "replay-15",
    "replay-30": "replay-30",
    "replay-5": "replay-5",
    reply: "reply",
    "reply-all": "reply-all",
    reserved: "reserved",
    "reset-left": "reset-left",
    "reset-right": "reset-right",
    "rest-time": "rest-time",
    restart: "restart",
    restaurant: "restaurant",
    rewind: "rewind",
    "rewind-mini": "rewind-mini",
    "rewind-start": "rewind-start",
    "rewind-start-mini": "rewind-start-mini",
    rfid: "rfid",
    rhythm: "rhythm",
    riding: "riding",
    "road-map": "road-map",
    roadster: "roadster",
    "robot-2": "robot",
    "rocket-2": "rocket",
    "rotate-lock": "rotate-lock",
    route: "route",
    router: "router",
    rss: "rss",
    ruler: "ruler",
    run: "run",
    safari: "safari",
    safe: "safe",
    sailboat: "sailboat",
    "save-2": "save",
    scales: "scales",
    "scan-2": "scan",
    school: "school",
    scissors: "scissors",
    "scissors-cut": "scissors-cut",
    screenshot: "screenshot",
    "scroll-to-bottom": "scroll-to-bottom",
    "sd-card": "sd-card",
    search: "search",
    "search-eye": "search-eye",
    "secure-payment": "secure-payment",
    seedling: "seedling",
    "send-ins": "send-ins",
    "send-plane": "send-plane",
    sensor: "sensor",
    seo: "seo",
    server: "server",
    service: "service",
    "service-bell": "service-bell",
    "settings-3": "settings",
    shadow: "shadow",
    "shake-hands": "shake-hands",
    shape: "shape",
    shapes: "shapes",
    share: "share",
    "share-circle": "share-circle",
    "share-forward": "share-forward",
    shield: "shield",
    "shield-check": "shield-check",
    "shield-cross": "shield-cross",
    "shield-flash": "shield-flash",
    "shield-keyhole": "shield-keyhole",
    "shield-star": "shield-star",
    "shield-user": "shield-user",
    shining: "shining",
    ship: "ship",
    shirt: "shirt",
    "shopping-bag": "shopping-bag",
    "shopping-basket": "shopping-basket",
    "shopping-cart-2": "shopping-cart",
    showers: "showers",
    shuffle: "shuffle",
    "shut-down": "shut-down",
    "side-bar": "side-bar",
    "sidebar-fold": "sidebar-fold",
    "sidebar-unfold": "sidebar-unfold",
    //"signal-cellular-3": "signal-cellular",
    //"signal-cellular-off": "signal-cellular-off",
    "signal-tower": "signal-tower",
    "signal-wifi": "signal-wifi",
    "signal-wifi-error": "signal-wifi-error",
    "signal-wifi-off": "signal-wifi-off",
    signpost: "signpost",
    "sim-card": "sim-card",
    sip: "sip",
    "skip-back": "skip-back",
    "skip-back-mini": "skip-back-mini",
    "skip-down": "skip-down",
    "skip-forward": "skip-forward",
    "skip-forward-mini": "skip-forward-mini",
    "skip-left": "skip-left",
    "skip-right": "skip-right",
    "skip-up": "skip-up",
    skull: "skull",
    skype: "skype",
    slack: "slack",
    slice: "slice",
    slideshow: "slideshow",
    "slow-down": "slow-down",
    smartphone: "smartphone",
    snapchat: "snapchat",
    snowflake: "snowflake",
    snowy: "snowy",
    sofa: "sofa",
    "sound-module": "sound-module",
    soundcloud: "soundcloud",
    //"space-ship-2": "space-ship",
    spam: "spam",
    sparkling: "sparkling",
    speak: "speak",
    speaker: "speaker",
    spectrum: "spectrum",
    //"speech-to-text": "speech-to-text",
    speed: "speed",
    "speed-up": "speed-up",
    spotify: "spotify",
    spy: "spy",
    square: "square",
    stack: "stack",
    "stack-overflow": "stack-overflow",
    // "stacked-chart": "stacked-chart",
    stackshare: "stackshare",
    stairs: "stairs",
    star: "star",
    "star-half": "star-half",
    "star-off": "star-off",
    steam: "steam",
    "steering-2": "steering",
    stethoscope: "stethoscope",
    "sticky-note": "sticky-note",
    "sticky-note-add": "sticky-note-add",
    stock: "stock",
    stop: "stop",
    "stop-circle": "stop-circle",
    "stop-large": "stop-large",
    store: "store",
    //subreddit: "subreddit",
    subtract: "subtract",
    subway: "subway",
    "subway-wifi": "subway-wifi",
    suitcase: "suitcase",
    sun: "sun",
    "sun-cloudy": "sun-cloudy",
    "sun-foggy": "sun-foggy",
    supabase: "supabase",
    "surgical-mask": "surgical-mask",
    "surround-sound": "surround-sound",
    survey: "survey",
    svelte: "svelte",
    swap: "swap",
    "swap-2": "swap-2",
    switch: "switch",
    sword: "sword",
    syringe: "syringe",
    "t-box": "t-box",
    "t-shirt": "t-shirt",
    "t-shirt-air": "t-shirt-air",
    table: "table",
    "table-alt": "table-alt",
    tablet: "tablet",
    "tailwind-css": "tailwind-css",
    takeaway: "takeaway",
    taobao: "taobao",
    tape: "tape",
    //target: "target",
    task: "task",
    taxi: "taxi",
    "taxi-wifi": "taxi-wifi",
    team: "team",
    "telegram-2": "telegram",
    "temp-cold": "temp-cold",
    "temp-hot": "temp-hot",
    tent: "tent",
    terminal: "terminal",
    "terminal-window": "terminal-window",
    "test-tube": "test-tube",
    // "text-to-speech": "text-to-speech",
    thermometer: "thermometer",
    threads: "threads",
    "thumb-down": "thumb-down",
    "thumb-up": "thumb-up",
    thunderstorms: "thunderstorms",
    ticket: "ticket",
    tiktok: "tiktok",
    time: "time",
    "time-zone": "time-zone",
    timer: "timer",
    "timer-flash": "timer-flash",
    todo: "todo",
    toggle: "toggle",
    "token-swap": "token-swap",
    tools: "tools",
    tooth: "tooth",
    tornado: "tornado",
    trademark: "trademark",
    "traffic-light": "traffic-light",
    train: "train",
    "train-wifi": "train-wifi",
    travesti: "travesti",
    "treasure-map": "treasure-map",
    tree: "tree",
    trello: "trello",
    triangle: "triangle",
    "triangular-flag": "triangular-flag",
    trophy: "trophy",
    truck: "truck",
    tumblr: "tumblr",
    tv: "tv",
    twitch: "twitch",
    twitter: "twitter",
    "twitter-x": "twitter-x",
    typhoon: "typhoon",
    "u-disk": "u-disk",
    ubuntu: "ubuntu",
    umbrella: "umbrella",
    uninstall: "uninstall",
    unpin: "unpin",
    unsplash: "unsplash",
    upload: "upload",
    "upload-cloud-2": "upload-cloud",
    //upwork: "upwork",
    usb: "usb",
    user: "user",
    "user-add": "user-add",
    "user-community": "user-community",
    "user-follow": "user-follow",
    "user-forbid": "user-forbid",
    "user-heart": "user-heart",
    "user-location": "user-location",
    "user-minus": "user-minus",
    "user-received": "user-received",
    "user-search": "user-search",
    "user-settings": "user-settings",
    "user-shared": "user-shared",
    "user-smile": "user-smile",
    "user-star": "user-star",
    "user-unfollow": "user-unfollow",
    "user-voice": "user-voice",
    vercel: "vercel",
    "verified-badge": "verified-badge",
    video: "video",
    "video-add": "video-add",
    "video-chat": "video-chat",
    "video-download": "video-download",
    "video-off": "video-off",
    "video-on": "video-on",
    "video-upload": "video-upload",
    vidicon: "vidicon",
    vimeo: "vimeo",
    vip: "vip",
    "vip-crown": "vip-crown",
    "vip-diamond": "vip-diamond",
    virus: "virus",
    visa: "visa",
    vk: "vk",
    "voice-recognition": "voice-recognition",
    voiceprint: "voiceprint",
    "volume-down": "volume-down",
    "volume-mute": "volume-mute",
    "volume-off-vibrate": "volume-off-vibrate",
    "volume-up": "volume-up",
    "volume-vibrate": "volume-vibrate",
    vuejs: "vuejs",
    walk: "walk",
    wallet: "wallet",
    "water-flash": "water-flash",
    "water-percent": "water-percent",
    webcam: "webcam",
    webhook: "webhook",
    wechat: "wechat",
    "wechat-channels": "wechat-channels",
    "wechat-pay": "wechat-pay",
    weibo: "weibo",
    weight: "weight",
    whatsapp: "whatsapp",
    wheelchair: "wheelchair",
    wifi: "wifi",
    "wifi-off": "wifi-off",
    window: "window",
    windows: "windows",
    windy: "windy",
    "wireless-charging": "wireless-charging",
    women: "women",
    wordpress: "wordpress",
    // wrench: "wrench",
    xbox: "xbox",
    xing: "xing",
    xrp: "xrp",
    xtz: "xtz",
    youtube: "youtube",
    yuque: "yuque",
    zcool: "zcool",
    zhihu: "zhihu",
    "zoom-in": "zoom-in",
    "zoom-out": "zoom-out",
    zzz: "zzz",
};

export const AI_ICON_NO_TYPE = [
    "a-b",
    "ai",
    "ai-generate",
    "ai-generate-text",
    "align-bottom",
    "align-center",
    "align-justify",
    "align-left",
    "align-right",
    "align-top",
    "align-vertically",
    "asterisk",
    "attachment-2",
    "bold",
    "bring-forward",
    "bring-to-front",
    "calendar-view",
    "carousel-view",
    "code-block",
    "code-view",
    "cursor-hand",
    "custom-size",
    "delete-column",
    "delete-row",
    "double-quotes-l",
    "double-quotes-r",
    "draggable",
    "dropdown-list",
    "emphasis",
    "emphasis-cn",
    "english-input",
    "flow-chart",
    "focus-mode",
    "font-color",
    "font-family",
    "font-mono",
    "font-sans-serif",
    "font-serif",
    "font-size",
    "font-size-2",
    "font-size-ai",
    "format-clear",
    "formula",
    "functions",
    "gallery-view",
    "gallery-view-2",
    "h-1",
    "h-2",
    "h-3",
    "h-4",
    "h-5",
    "h-6",
    "hand",
    "hand-2",
    "hashtag",
    "heading",
    "indent-decrease",
    "indent-increase",
    "info-i",
    "input-cursor-move",
    "input-field",
    "insert-column-left",
    "insert-column-right",
    "insert-row-bottom",
    "insert-row-top",
    "italic",
    "kanban-view",
    "kanban-view-2",
    "letter-spacing-2",
    "line-height",
    "line-height-2",
    "link",
    "link-m",
    "link-unlink",
    "link-unlink-m",
    "list-check",
    "list-check-2",
    "list-check-3",
    "list-indefinite",
    "list-ordered",
    "list-ordered-2",
    "list-radio",
    "list-unordered",
    "list-view",
    "merge-cells-horizontal",
    "merge-cells-vertical",
    "mind-map",
    "node-tree",
    "number-0",
    "number-1",
    "number-2",
    "number-3",
    "number-4",
    "number-5",
    "number-6",
    "number-7",
    "number-8",
    "number-9",
    "omega",
    "organization-chart",
    "overline",
    "page-separator",
    "paragraph",
    "pinyin-input",
    "question-mark",
    "quote-text",
    "rounded-corner",
    "send-backward",
    "send-to-back",
    "separator",
    "single-quotes-l",
    "single-quotes-r",
    "sketching",
    "slash-commands",
    "slash-commands-2",
    "slideshow-view",
    "sort-alphabet-asc",
    "sort-alphabet-desc",
    "sort-asc",
    "sort-desc",
    "sort-number-asc",
    "sort-number-desc",
    "space",
    "split-cells-horizontal",
    "split-cells-vertical",
    "square-root",
    "stacked-view",
    "strikethrough",
    "subscript",
    "subscript-2",
    "superscript",
    "superscript-2",
    "table-2",
    "table-3",
    "table-view",
    "text",
    "text-block",
    "text-direction-l",
    "text-direction-r",
    "text-snippet",
    "text-spacing",
    "text-wrap",
    "timeline-view",
    "translate",
    "translate-2",
    "translate-ai",
    "translate-ai-2",
    "underline",
    "wubi-input",
] as const;

export const AI_ICONS = {
    ...AI_ICON_BASE,
    ...Object.fromEntries(AI_ICON_NO_TYPE.map(name => [name, name])),
} as const;

export type AiIconType = keyof typeof AI_ICONS;
